>#
# Copyright (C) 2015-2017 Nico Kadel-Garcia <nkadel@gmail.com>
#
# Makefile for chef-local - pull from git, run Berksfile, and run chef
#	Note logging of verbose log files in pull.out, chef-local.out, etc.

# Berkshelf requires UTF capable LANG
LANG = en_US.UTF8

# Insist on using /bin/pwd for "make -C"
PWD = "`/bin/pwd`"

# Ensure components are installed
BERKS = /usr/bin/berks
CHEFCLIENT = /usr/bin/chef-client
CHEFLOCAL = $(CHEFCLIENT) --local-mode
CHEFETCDIR = /etc/chef

# berks install puts cookbooks here, local.rb finds them here
BERKSCOOKBOOKS = berks-cookbooks
# Default  foodcritic and testing tool location
COOKBOOKSLINK = cookbooks

# Node specific json file, if available
# Do not use $(HOSTNAME), not set for remote shell sesison
#HOST = `uname -n`
# Use --fqdn
HOST = `hostname --fqdn`
DEFAULTNODE = $(PWD)/nodes-local/default.json.tmpl
NODE = $(PWD)/nodes-local/$(HOST).json
# chef-local configuration to find nodes, databags
LOCAL = local.rb

# chef-local configured to use these by default
NODELINK = $(CHEFETCDIR)/node.json

BRANCH = "`git branch | grep ^'*' | awk '{print $$2}'`"

all: oscheck pull install vendor run

# Optional wrapper to merely set up local config symlinks
links: $(NODELINK) $(COOKBOOKSLINK)

# Verify RHEL style OS, Amazon Linux uses /etc/os-release
.PHONY: oscheck
oscheck:
	@test -s /etc/redhat-release || test -s /etc/os-release

$(BERKS) $(CHEFCLIENT):
	@echo Error: $@ missing, install chefdk with RPM

# Default chef-local location for config files
$(CHEFETCDIR):
	install -d -m770 -oroot -groot $@

.PHONY: pull
pull: .git /usr/bin/git
	@rm -f pull.out
	git pull --all | tee pull.out || \
	    git pull origin $(BRANCH) | tee pull.out

/usr/bin/git:
	@echo "Error: git missing, run 'yum install git'"
	@exit 1

.PHONY: berks
install: $(BERKS) Berksfile
	@rm -f install.out
	$(BERKS) install 2>&1 | tee install.out

.PHONY: vendor
vendor: $(BERKS)
	$(BERKS) vendor


.PHONY: local
local: $(LOCAL)
$(LOCAL): $(LOCAL).in Makefile
	sed "s|@@@PWD@@@|$(PWD)|g" $(LOCAL).in > $@

# Set up node based on templates from symlinks
.PHONY: node
node: $(NODE)
$(NODE):
	@ echo setting up $(NODE)
	@case $(HOST) in \
	    template1-*) \
		echo "Linking template1.json.tmpl template to $(NODE)"; \
		ln -sf ../nodes-local/template1.json.tmpl $(NODE); \
		;; \
	esac

# Set up node based on templates from symlinks
.PHONY: nodelink
nodelink: $(NODELINK)
.PHONY: $(NODELINK)
$(NODELINK): $(CHEFETCDIR) $(NODE)
	@echo Checking link: $@
	@if [ -s "$(NODE)" ]; then \
	    if [ "`readlink --canonicalize $(NODELINK)`" != $(NODE) ]; then \
		echo "Setting $(NODE) link"; \
	        ln -sf $(NODE) $(NODELINK); \
	    fi; \
	else \
	    echo "Warning: $(NODE) not found, using $(DEFAULTNODE)"; \
	    if [ "`readlink --canonicalize $(NODELINK)`" != $(DEFAULTNODE) ]; then \
		echo "Setting $(DEFAULTNODE) link"; \
	        ln -sf $(DEFAULTNODE) $(NODELINK); \
	    fi; \
	fi

.PHONY: $(COOKBOOKSLINK)
$(COOKBOOKSLINK): $(BERKSCOOKBOOKS)
	@echo Checking link: $@
	@if [ "`readlink --canonicalize $(COOKBOOKSLINK)`" != $(PWD)/$(BERKSCOOKBOOKS) ]; then \
	    ln -sf $(PWD)/$(BERKSCOOKBOOKS) $(COOKBOOKSLINK); \
	fi

.PHONY: run
# Flush stacktraces before starting
# Leave obvious failure report at chef-local.fail.out for auditing,
# move to chef-local.out only on success
run: links
	@rm -f /var/cache/chef/chef-stackrace.out
	@rm -f chef-local.out chef-local.fail.out
	@echo
	@echo "Running: $(CHEFLOCAL) --config $(LOCAL) -j $(NODELINK), logs in chef-local.out"
	$(CHEFLOCAL) --config $(LOCAL) -j $(NODELINK) 2>&1 | tee chef-local.fail.out
	mv -f chef-local.fail.out chef-local.out

# Phony, placeholder for berks-cookbooks generated by "berks vendor"
.PHONY: $(BERKSCOOKBOOKS)


clean:
	rm -rf berks-cookbooks
	rm -f *.out
	rm -rf local-mode-cache

distclean: clean
	rm -rf nodes
	git clean -x -d -f

